-- ============================================================================
-- POS GAP PLAN — DATABASE ALIGNMENT MIGRATION
-- Companion to: plan.md/odoo-pos-gap-audit-plan.md (Phase 0)
-- Date: 2026-08-23
--
-- RESULT OF PHASE 0 VERIFICATION (live probes via PostgREST):
--   orders            -> order_type, subtotal, discount, discount_type,
--                        tax_rate, tax, tip, change_given, receipt_number,
--                        payment_method, table_id  ALL EXIST  ✅
--   pos_sessions      -> table exists (opening_float, expected_cash,
--                        actual_cash, status, opened/closed)        ✅
--   restaurant_tables -> table exists (table_number, capacity, status,
--                        current_order_id)                          ✅
--   payments          -> direction, party_type, order_id, method    ✅
--   order_items       -> notes column does NOT exist (deferred — see §3)
--
-- CONCLUSION: NO destructive or additive DDL is required for plan Steps 1–2
-- (refunds + reorder suggestions). Both ship on existing columns.
-- This file exists to (a) document that, (b) provide the RLS checks the app
-- cannot perform remotely, and (c) pre-stage the one future migration.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. RUN THESE CHECKS IN THE SUPABASE SQL EDITOR (read-only, safe)
-- ----------------------------------------------------------------------------
-- 1a. Confirm nullability/defaults on orders (the NOT NULL anomaly):
--     sales work today while submitSale() inserts only total_amount, so these
--     must carry defaults. Record the output next to Phase 0 in the plan doc.
--
-- select column_name, is_nullable, data_type, column_default
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'orders'
-- order by ordinal_position;
--
-- 1b. Confirm RLS is enabled on every table the POS plan will touch.
--     Expected: rls_enabled = true AND at least one business-scoped policy.
--
-- select c.relname as table_name, c.relrowsecurity as rls_enabled,
--        count(p.policyname) as policy_count
-- from pg_class c
-- join pg_namespace n on n.oid = c.relnamespace
-- left join pg_policies p
--        on p.tablename = c.relname and p.schemaname = n.nspname
-- where n.nspname = 'public'
--   and c.relname in ('orders','order_items','payments','products',
--                     'stock_movements','restaurant_tables','pos_sessions')
-- group by 1, 2
-- order by 1;
--
-- If restaurant_tables or pos_sessions show rls_enabled = false, enable RLS
-- and add policies mirroring whichever pattern `orders` uses BEFORE any app
-- code touches them (plan Step 5). Template only — match the real pattern:
--
-- alter table public.restaurant_tables enable row level security;
-- create policy tenant_all_restaurant_tables
--   on public.restaurant_tables
--   for all
--   using (
--     business_id in (
--       select business_id from public.app_users
--       where user_id = auth.uid()
--     )
--   );
-- -- repeat shape for pos_sessions

-- ----------------------------------------------------------------------------
-- 2. NO CHANGES REQUIRED FOR STEPS 1–2 (refunds, reorder suggestions)
-- ----------------------------------------------------------------------------
-- Refunds write:
--   orders.status = 'refunded'          (status column exists)
--   payments row: direction='out',
--                 party_type='customer',
--                 order_id=<refunded order>,
--                 method in (cash|bank_transfer|mobile_money)
--                                       (all existing columns; app already
--                                        writes direction='in' today)
-- Reorder suggestions read products.stock_qty / low_stock_threshold /
-- cost_price and reuse submitPurchase() unchanged.

-- ----------------------------------------------------------------------------
-- 3. DEFERRED (uncomment ONLY when kitchen-notes scope is confirmed, Step 6)
-- ----------------------------------------------------------------------------
-- Safe additive change, but ground rule #8 says one capability at a time and
-- nothing consumes it yet:
--
-- alter table public.order_items
--   add column if not exists notes text;
